# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
local: &local
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
development: *local
test: *local
